services:
  - type: web
    name: autoemotion-server
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
  # Build from Dockerfile inside the server/ subdirectory
  rootDir: server
  dockerfilePath: Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    buildFilter:
      paths:
        - server/**
        - render.yaml
