name: autoemotion_server
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  http: ^1.2.2

# Optional dev tooling
dev_dependencies:
  lints: ^5.1.1
